name:                subtitles-checker
version:             0.1.0.0
github:              "eehah5ru/subtitles-checker"
license:             BSD3
author:              "nicolay spesivtsev"
maintainer:          "nicola.spesivcev@gmail.com"
copyright:           "nicolay spesivstev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            science fiction

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/eehah5ru/subtitles-checker#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  subtitles-checker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subtitles-checker

tests:
  subtitles-checker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subtitles-checker
